# Generated by Django 4.2.1 on 2023-06-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=50, verbose_name='Owner')),
                ('license_plate', models.CharField(db_index=True, max_length=50, verbose_name='License plate')),
                ('vin_code', models.CharField(db_index=True, max_length=50, verbose_name='VIN code')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'ordering': ['owner'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=50, verbose_name='Brand')),
                ('model', models.CharField(db_index=True, max_length=50, verbose_name='Model')),
                ('year', models.PositiveIntegerField(blank=True, default=2000, null=True, verbose_name='Year')),
                ('engine', models.CharField(blank=True, max_length=50, null=True, verbose_name='Engine')),
            ],
            options={
                'verbose_name': 'car model',
                'verbose_name_plural': 'car models',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Data')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=18, null=True, verbose_name='Amount')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='servisas.car', verbose_name='car')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('price', models.FloatField(verbose_name='price')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=20, verbose_name='Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='servisas.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order entry',
                'verbose_name_plural': 'order entries',
                'ordering': ['price', 'quantity'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=18, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.RemoveField(
            model_name='automobilis',
            name='automobilio_modelis',
        ),
        migrations.RemoveField(
            model_name='uzsakymas',
            name='automobilis',
        ),
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='paslauga',
        ),
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='uzsakymas',
        ),
        migrations.DeleteModel(
            name='AutomobilioModelis',
        ),
        migrations.DeleteModel(
            name='Automobilis',
        ),
        migrations.DeleteModel(
            name='Paslauga',
        ),
        migrations.DeleteModel(
            name='Uzsakymas',
        ),
        migrations.DeleteModel(
            name='UzsakymoEilute',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='servisas.service', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='servisas.carmodel', verbose_name='model'),
        ),
    ]
